"""
PakLaw AI — Research Report ORM Model

Stores structured legal research reports generated by the AI.
"""

import uuid
from datetime import datetime
from enum import Enum

from sqlalchemy import DateTime, Float, ForeignKey, Integer, JSON, String, Text, Boolean, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.database import Base


class ReportStatus(str, Enum):
    QUEUED = "queued"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class ExportFormat(str, Enum):
    PDF = "pdf"
    DOCX = "docx"
    MARKDOWN = "markdown"
    JSON = "json"


class ResearchReport(Base):
    """AI-generated structured legal research report."""

    __tablename__ = "research_reports"

    id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    conversation_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("conversations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Research query
    research_query: Mapped[str] = mapped_column(Text, nullable=False)
    language: Mapped[str] = mapped_column(String(10), default="en")

    # Status
    status: Mapped[ReportStatus] = mapped_column(
        String(20), default=ReportStatus.QUEUED, index=True
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Report content (structured JSON)
    title: Mapped[str | None] = mapped_column(String(500), nullable=True)
    executive_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    legal_issues: Mapped[list | None] = mapped_column(JSON, nullable=True)
    applicable_laws: Mapped[list | None] = mapped_column(JSON, nullable=True)
    relevant_sections: Mapped[list | None] = mapped_column(JSON, nullable=True)
    judgments: Mapped[list | None] = mapped_column(JSON, nullable=True)
    conflicts_detected: Mapped[list | None] = mapped_column(JSON, nullable=True)
    recommendations: Mapped[list | None] = mapped_column(JSON, nullable=True)
    citations: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # Full markdown content
    full_content_markdown: Mapped[str | None] = mapped_column(Text, nullable=True)

    # AI metadata
    model_used: Mapped[str | None] = mapped_column(String(100), nullable=True)
    confidence_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    documents_searched: Mapped[int] = mapped_column(Integer, default=0)
    sections_retrieved: Mapped[int] = mapped_column(Integer, default=0)
    generation_time_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Export files
    pdf_path: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    docx_path: Mapped[str | None] = mapped_column(String(1000), nullable=True)

    is_pinned: Mapped[bool] = mapped_column(Boolean, default=False)
    is_deleted: Mapped[bool] = mapped_column(Boolean, default=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="research_reports")  # type: ignore[name-defined]

    def __repr__(self) -> str:
        return f"<ResearchReport {self.id} [{self.status}]>"
