"""
PakLaw AI — Legal Research Report Router

Orchestrates long-running legal issue research workflows.
"""

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, status
from fastapi.responses import FileResponse

from app.dependencies.auth import get_current_user, get_user_repository
from app.models.user import User
from app.repositories.research import ResearchRepository
from app.schemas.research import (
    ExportRequest,
    ResearchListResponse,
    ResearchReportResponse,
    ResearchRequest,
)
from app.services.research import ResearchService

router = APIRouter(prefix="/research", tags=["Legal Research Mode"])


async def get_research_repository(
    db = Depends(get_user_repository)
) -> ResearchRepository:
    from app.models.research import ResearchReport
    return ResearchRepository(ResearchReport, db.db)


async def get_research_service(
    repo: Annotated[ResearchRepository, Depends(get_research_repository)]
) -> ResearchService:
    return ResearchService(repo)


@router.post(
    "/report",
    response_model=ResearchReportResponse,
    status_code=status.HTTP_202_ACCEPTED,
)
async def generate_research_report(
    request: ResearchRequest,
    current_user: User = Depends(get_current_user),
    research_service: ResearchService = Depends(get_research_service),
):
    """
    Submit a legal issue for comprehensive research and structured analysis.
    Fires a background Celery task and returns a pending report tracking token.
    """
    return await research_service.create_research_report(request, current_user.id)


@router.get("/reports", response_model=ResearchListResponse)
async def list_research_reports(
    page: int = 1,
    page_size: int = 10,
    current_user: User = Depends(get_current_user),
    research_service: ResearchService = Depends(get_research_service),
):
    """List historical legal research reports generated by the user."""
    return await research_service.list_reports(current_user.id, page, page_size)


@router.get("/reports/{report_id}", response_model=ResearchReportResponse)
async def get_research_report(
    report_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    research_service: ResearchService = Depends(get_research_service),
):
    """Retrieve details and legal findings of a generated research report."""
    return await research_service.get_report(report_id, current_user.id)


@router.delete("/reports/{report_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_research_report(
    report_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    research_service: ResearchService = Depends(get_research_service),
):
    """Soft delete a generated research report."""
    await research_service.delete_report(report_id, current_user.id)


@router.post("/export")
async def export_research_report(
    request: ExportRequest,
    current_user: User = Depends(get_current_user),
    research_service: ResearchService = Depends(get_research_service),
):
    """Export a research report as a compiled PDF or DOCX file."""
    file_path = await research_service.export_report(
        request.report_id, request.format, current_user.id
    )
    
    filename = f"PakLaw_Research_Report_{request.report_id}.{request.format.value}"
    
    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/octet-stream",
    )
